### ISSUE TITLE
Live editing broken in docs

### ISSUE THREAD

**Issue by facelessuser** [color-js/color.js#429]
As title mentions, none of the live examples allow editing.

**Comment by MysteryBlokHed** [comment]
Weird—for some reason I can edit them just fine in Firefox, but it doesn't work in Chrome

**Comment by MysteryBlokHed** [comment]
This is what the inspector looks like in Chrome:

![Screenshot of a color.js documentation page in Chrome](https://github.com/color-js/color.js/assets/13910387/bdc86125-838d-4b90-ad00-242bed2d4603)

And this is what it looks like in Firefox:

![Screenshot of the same documentation page in Firefox](https://github.com/color-js/color.js/assets/13910387/4500ec8e-b322-459b-8fe3-4516c71f3e80)

There seems to be a `<textarea>` that's completely missing in Chrome, and Chrome has individual `<span>`s for every token. Not really sure what might be causing that.

**Comment by MysteryBlokHed** [comment]
After checking again, it looks like it actually seemingly randomly goes back and forth between working and not working after refreshes (on Firefox).

**Comment by facelessuser** [comment]
I don't know their document system well enough to debug. If it had been a clear issue originating from the color library, I would have spent more time looking at it. I saw some cross origin complaints and a shadow root complaint:

```
prism-live.js?load=javascript:1 Uncaught (in promise) TypeError: Failed to resolve module specifier './prism-live.mjs'. The base URL is about:blank because import() is called from a CORS-cross-origin script.
    at prism-live.js?load=javascript:1:1
```

```
Uncaught TypeError: Cannot read properties of null (reading 'shadowRoot')
    at handleNodesDeep (content.js:208:22)
    at handleDocument (content.js:164:25)
    at load (content.js:59:17)
    at content.js:200:55
```

**Comment by facelessuser** [comment]
The issue seems to be the CORS error. Running chrome as below fixed the issue.

```
open /Applications/Google\ Chrome.app --args --user-data-dir="/var/tmp/chrome-dev-disabled-security" --disable-web-security --disable-site-isolation-trials
```

Safari did not seem to have an issue, and I was able to reproduce the intermittent issue with Firefox. I assume fixing the cores issue with Prism will likely get things working everywhere.

**Comment by LeaVerou** [comment]
I recently switched Prism Live to use ESM and I think that's what broke this. Should be an easy fix.

**Comment by facelessuser** [comment]
Ok, that explains it. I was trying to figure out what changed.

**Comment by LeaVerou** [comment]
Should be fixed now, sorry about that!

**Comment by facelessuser** [comment]
@LeaVerou It is working again! As a side note, I'm not sure if you are aware, but selections are invisible currently, it makes it difficult to select and copy specific things in examples. I assume it is a style regression, but I haven't looked into it too much yet.

**Comment by svgeesus** [comment]
I am getting some odd results in live editing, too 

![image](https://github.com/color-js/color.js/assets/2506926/1b9d6384-7b4e-4953-afe5-b4ee0d8bb4bc)

**Comment by facelessuser** [comment]
FYI, the selection issue seems to be chrome only.

**Comment by facelessuser** [comment]
It is only mac as well...

**Comment by jgerigmeyer** [comment]
The live editor is still (again?) broken for me in Chrome:

```
Uncaught (in promise) TypeError: Failed to resolve module specifier './prism-live.mjs?load=javascript'. The base URL is about:blank because import() is called from a CORS-cross-origin script.
    at prism-live.js?load=javascript:16:28
```

**Comment by facelessuser** [comment]
Yes, I noticed this as well.  Had not gotten around to commenting.

**Comment by LeaVerou** [comment]
Ugh, sorry about that. I’ll take a look. FWIW that should not hold up the release.
